### ISSUE TITLE
mirrormanager

### ISSUE THREAD

**Issue by brianjmurrell** [AlmaLinux/mirrors#401]
Are there any plans to move to or otherwise utilize [mirrormanager](https://fedoraproject.org/w/index.php?title=Infrastructure/MirrorManager&rd=MirrorManager)?

It does a really good job at solving the problem of making machines use local (private even, if desired) mirrors using the distro supplied "out of the box" `.repo` files -- no need to edit to set `baseurl`s etc.

**Comment by jonathanspw** [comment]
Hey Brian,

I'm not sure why we would at this point.  We built our mirrorlist system to serve geographically-closest mirrors first and local mirrors if local subnets are provided to mirrorlist (just like mirrormanager).

**Comment by brianjmurrell** [comment]
I didn't see any documentation on how one configures a local mirror and associates it with IP addresses/subnets.

**Comment by jonathanspw** [comment]
You are absolutely right!  It's something we've setup on our Azure mirrors and totally forgot to document, apparently.

You can add the following to your YAML for example:

```
subnets:
  - 192.168.1.0/24
```

You can also do it with ASNs:
```
asn: 1234
```

I'll make sure we get this documented properly soon.

**Comment by brianjmurrell** [comment]
> You can add the following to your YAML for example:

My YAML for what?  Does https://wiki.almalinux.org/Mirrors.html apply to private mirrors also?

**Comment by jonathanspw** [comment]
Yes I was referring to a repo config submitted to this repo in YAML format per the instructions you linked.

If you want the repo to be private-only and not be served to others via our mirrorlist then you can also add `private: yes` to the config and it will only be served for your subnets.

Building upon our [sample config](https://github.com/AlmaLinux/mirrors/blob/master/mirrors.d/repo.almalinux.org.yml) the additions would look like this:

```
name: repo.almalinux.org
address:
  http: http://repo.almalinux.org/almalinux/
  https: https://repo.almalinux.org/almalinux/
  rsync: rsync://rsync.repo.almalinux.org/almalinux
geolocation:
  country: DE
  state_province: Saxony
  city: Falkenstein
update_frequency: 1h
sponsor: AlmaLinux OS Foundation
sponsor_url: https://www.almalinux.org
email: hello@almalinux.org
subnets:
  - 192.168.0.0/24
private: yes
```

Does this cover your use-case?
