### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by mertkaracali** [AlmaLinux/mirrors#840]
I forked Mirror but it doesn't show up at mirrors.almalinux.org.

https://github.com/AlmaLinux/mirrors/blob/master/mirrors.d/mirror.ph.net.tr

**Comment by codyro** [comment]
Hello,

There may be a mistake in your mirror file causing this not to be listed. 

You'll want to adjust the following line(s): https://github.com/AlmaLinux/mirrors/blob/master/mirrors.d/mirror.ph.net.tr#L3-L4

```yaml
address:
  http: https://mirror.ph.net.tr/almalinux/
  https: https://mirror.ph.net.tr/almalinux/
```

Please note that in my example, I added `http` and `https` as your mirror appears to respond to both.
